#pragma once
#include "shaderlib/cshader.h"
class lux_debug_luxels_vs30_Static_Index
{
public:
	lux_debug_luxels_vs30_Static_Index(  )
	{
	}

	int GetIndex() const
	{
		return 0;
	}
};

#define shaderStaticTest_lux_debug_luxels_vs30 1


class lux_debug_luxels_vs30_Dynamic_Index
{
public:
	lux_debug_luxels_vs30_Dynamic_Index(  )
	{
	}

	int GetIndex() const
	{
		return 0;
	}
};

#define shaderDynamicTest_lux_debug_luxels_vs30 1

