#pragma once
#include "shaderlib/cshader.h"
class lux_blurgaussian_ps30_Static_Index
{
public:
	lux_blurgaussian_ps30_Static_Index(  )
	{
	}

	int GetIndex() const
	{
		return 0;
	}
};

#define shaderStaticTest_lux_blurgaussian_ps30 1


class lux_blurgaussian_ps30_Dynamic_Index
{
public:
	lux_blurgaussian_ps30_Dynamic_Index(  )
	{
	}

	int GetIndex() const
	{
		return 0;
	}
};

#define shaderDynamicTest_lux_blurgaussian_ps30 1

