//===================== File of the LUX Shader Project =====================//
//
//	Initial D.	:	24.09.2025 DMY
//	Last Change :	 30.01.2026 DMY
//
//	Purpose of this File : Turns Magic Numbers into Macros
//
//==========================================================================//

#ifndef LUX_REGISTERMAP_PS_H_
#define LUX_REGISTERMAP_PS_H_

// Starting with float Constants
// ps20b Registers:

// NOTE: Ambient Cube shares same Registers as ProjTex since you don't get both at the same Time.
/*	c0
	c1
	c2
	c3
	c4
	c5
	c6
	c7
	c8
	c9
	c10
	c11
	c12 */
#define LUX_PS_FLOAT_AMBIENTCUBE			REGISTER_FLOAT_013
/*	c14
	c15
 	c16 */
#define LUX_PS_FLOAT_PROJTEX_TWEAKS			REGISTER_FLOAT_017
#define LUX_PS_FLOAT_PROJTEX_ATTEN			REGISTER_FLOAT_018
#define LUX_PS_FLOAT_PROJTEX_COLOR			REGISTER_FLOAT_019
#define LUX_PS_FLOAT_LIGHTDATA				REGISTER_FLOAT_019
#define LUX_PS_FLOAT_PROJTEX_POSITION		REGISTER_FLOAT_020
#define LUX_PS_FLOAT_PROJTEX_MATRIX			REGISTER_FLOAT_021
/*	c22	LightData[2] - ProjTex Matrix
	c23	LightData[3] - ProjTex Matrix
	c24	LightData[4] - ProjTex Matrix
	c25	LightData[5] */
#define LUX_PS_FLOAT_LUMINANCE_GAMMA		REGISTER_FLOAT_025
#define LUX_PS_FLOAT_CAMERAPOSITION			REGISTER_FLOAT_026
#define LUX_PS_FLOAT_FOGPARAMETERS			REGISTER_FLOAT_027
#define LUX_PS_FLOAT_MODULATIONCONSTANTS	REGISTER_FLOAT_028
//	c29 g_LinearFogColor
//	c30 g_LightScale
#define LUX_PS_FLOAT_DEFAULTCONTROLS		REGISTER_FLOAT_031

// ps30 Registers:

#define LUX_PS_FLOAT_COLOR_FACTORS			REGISTER_FLOAT_032
#define LUX_PS_FLOAT_DETAIL_FACTORS			REGISTER_FLOAT_033
#define LUX_PS_FLOAT_DETAIL_BLENDMODE		REGISTER_FLOAT_034
#define LUX_PS_FLOAT_SELFILLUM_FACTORS		REGISTER_FLOAT_035
#define LUX_PS_FLOAT_SELFILLUM_FRESNEL		REGISTER_FLOAT_036
#define LUX_PS_FLOAT_ENVMAP_TINT			REGISTER_FLOAT_037
#define LUX_PS_FLOAT_ENVMAP_FACTORS			REGISTER_FLOAT_038
#define LUX_PS_FLOAT_ENVMAP_CONTROLS		REGISTER_FLOAT_039
#define LUX_PS_FLOAT_ENVMAP_FRESNEL			REGISTER_FLOAT_040
#define LUX_PS_FLOAT_ENVMAP_POSITION		REGISTER_FLOAT_041
#define LUX_PS_FLOAT_ENVMAP_MATRIX			REGISTER_FLOAT_042
#define LUX_PS_FLOAT_ENVMAP_MATRIX_2		REGISTER_FLOAT_043
#define LUX_PS_FLOAT_ENVMAP_MATRIX_3		REGISTER_FLOAT_044
#define LUX_PS_FLOAT_PHONG_TINT				REGISTER_FLOAT_045
#define LUX_PS_FLOAT_PHONG_FRESNEL			REGISTER_FLOAT_046
#define LUX_PS_FLOAT_PHONG_CONTROLS			REGISTER_FLOAT_047
#define LUX_PS_FLOAT_PHONG_MINLIGHT_BOOST	REGISTER_FLOAT_048

// Stock Float Registers:
#define STOCK_PS_FLOAT_LINEARFOGCOLOR		REGISTER_FLOAT_029
#define STOCK_PS_FLOAT_LIGHTSCALE			REGISTER_FLOAT_030

// Boolean Registers:
#define LUX_PS_BOOL_HALFLAMBERT					REGISTER_BOOL_00
#define LUX_PS_BOOL_LIGHTWARPTEXTURE			REGISTER_BOOL_01
// FREE
// FREE
#define LUX_PS_BOOL_PHONG_BASEMAPALPHAMASK		REGISTER_BOOL_04
#define LUX_PS_BOOL_PHONG_ALBEDOTINT			REGISTER_BOOL_05
#define LUX_PS_BOOL_PHONG_FLATNORMAL			REGISTER_BOOL_06
#define LUX_PS_BOOL_PHONG_RIMLIGHTMASK			REGISTER_BOOL_07
#define LUX_PS_BOOL_PHONG_BASEMAPLUMINANCEMASK	REGISTER_BOOL_08
#define LUX_PS_BOOL_PHONG_EXPONENTTEXTUREMASK	REGISTER_BOOL_09
#define LUX_PS_BOOL_PHONG_RIMLIGHT				REGISTER_BOOL_10
#define LUX_PS_BOOL_PHONG_WARPTEXTURE			REGISTER_BOOL_11
#define LUX_PS_BOOL_VERTEXCOLOR					REGISTER_BOOL_12
#define LUX_PS_BOOL_HEIGHTFOG					REGISTER_BOOL_13	
#define LUX_PS_BOOL_RADIALFOG					REGISTER_BOOL_14	
#define LUX_PS_BOOL_DEPTHTODESTALPHA			REGISTER_BOOL_15	

#endif // LUX_REGISTERMAP_PS_H_