//===================== File of the LUX Shader Project =====================//
//
//	Initial D.	:	12.01.2025 DMY
//	Last Change :	 30.01.2026 DMY
//
//==========================================================================//

#ifndef LUX_UNLITGENERIC_REGISTERMAP_H_
#define LUX_UNLITGENERIC_REGISTERMAP_H_

// Constant Register Macros for the UnlitGeneric Shader
// This requires lux_registermap_.. to be included before this File!

#define UNLITGENERIC_ENVMAP_TINT			REGISTER_FLOAT_002
#define UNLITGENERIC_ENVMAP_FRESNEL			REGISTER_FLOAT_003
#define UNLITGENERIC_ENVMAP_FACTORS			REGISTER_FLOAT_004
#define UNLITGENERIC_ENVMAP_POSITION		REGISTER_FLOAT_005
#define UNLITGENERIC_ENVMAP_MATRIX			REGISTER_FLOAT_006
/* Matrix Rows
*/
#define UNLITGENERIC_ENVMAP_CONTROLS		REGISTER_FLOAT_009
#define UNLITGENERIC_DETAIL_TINT			REGISTER_FLOAT_010
#define UNLITGENERIC_DETAIL_MODE			REGISTER_FLOAT_011
#define UNLITGENERIC_DA_GLOWPARAMS			REGISTER_FLOAT_012
#define UNLITGENERIC_DA_GLOWCOLOR			REGISTER_FLOAT_013
#define UNLITGENERIC_DA_PARAMS				REGISTER_FLOAT_014
#define UNLITGENERIC_DA_OUTLINECOLOR		REGISTER_FLOAT_015
#define UNLITGENERIC_DA_OUTLINEPARARMS		REGISTER_FLOAT_016

#define UNLITGENERIC_BOOL_VERTEXALPHA		REGISTER_BOOL_03

#endif // LUX_UNLITGENERIC_REGISTERMAP_H_