//===================== File of the LUX Shader Project =====================//
//
//	Initial D.	:	12.01.2025 DMY
//	Last Change :	 30.01.2026 DMY
//
//==========================================================================//

#ifndef LUX_INFECTED_REGISTERMAP_H_
#define LUX_INFECTED_REGISTERMAP_H_

// Constant Register Macros for the Infected Shader
// This requires lux_registermap_.. to be included before this File!

#define INFECTED_RANDOMISATION		REGISTER_FLOAT_000
#define INFECTED_BLOODCONTROLS1		REGISTER_FLOAT_001
#define INFECTED_BLOODCONTROLS2		REGISTER_FLOAT_002
#define INFECTED_PHONGCONTROLS1		REGISTER_FLOAT_003
#define INFECTED_PHONGCONTROLS2		REGISTER_FLOAT_004
#define INFECTED_EYEGLOWCONTROLS	REGISTER_FLOAT_005
#define INFECTED_DETAILCONTROLS		REGISTER_FLOAT_006
#define INFECTED_CUTOUTCONTROLS1	REGISTER_FLOAT_007
#define INFECTED_CUTOUTCONTROLS2	REGISTER_FLOAT_008
#define INFECTED_CUTOUTCONTROLS3	REGISTER_FLOAT_009
#define INFECTED_AMBIENTCUBE		REGISTER_FLOAT_010
#define INFECTED_LIGHTINFO			REGISTER_FLOAT_016

#endif // LUX_INFECTED_REGISTERMAP_H_