name: Push Dev Builds

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Download Windows TFGrub artifact
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          name: tfgrub-windows-tfgrub_folder
          path: artifact

      - name: Clone repo
        run: |
          git clone https://x-access-token:${{ secrets.TFGRUB_DEV_TOKEN }}@github.com/Grub-Fortress/grub_fortress_dev.git target_repo

      - name: Replace repo contents with a new build
        run: |
          cd target_repo
          find . -mindepth 1 -maxdepth 1 ! -name ".git" -exec rm -rf {} +
          cp -r ../artifact/* .

      - name: Commit and push
        run: |
          cd target_repo
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Push commit: ${{ github.event.workflow_run.id }}" || echo "No changes"
          git push
